Add initial files
turbot/steampipe-plugin-guardrails pull request #1
Opened 2023-07-27 12:49 UTC by misraved

2023-07-27 19:51 UTC, cbruno10 requested changes
@misraved Please see review comments. I didn't comment on all instances of changing Turbot -> Guardrails or adding the word "Guardrails" in front of "Turbot", but added some comments that can be extrapolated to other instances.

2023-07-27 19:51 UTC, cbruno10 commented on CHANGELOG.md
> +## v0.10.0 [2023-03-22]
We can probably clear out all previous CHANGELOG options if we're using the next minor version from the Turbot plugin

2023-07-27 19:51 UTC, cbruno10 commented on README.md
> +Use SQL to query infrastructure including servers, networks, identity and more from Turbot Guardrails.
Is this description correct? I think we'd want to mention different resources

2023-07-27 19:51 UTC, cbruno10 commented on config/guardrails.spc
> +  # By default, Steampipe will use your Turbot profiles and credentials exactly
```suggestion
  # By default, Steampipe will use your Turbot Guardrails profiles and credentials exactly
```

I think we'd probably need similar updates here and in all other files/comments as well

2023-07-27 19:51 UTC, cbruno10 commented on config/guardrails.spc
> +  # Use an existing Turbot profile configured in ~/.config/turbot
Is this changing in the CLI? Assuming not, but worth checking

2023-07-27 19:51 UTC, cbruno10 commented on docs/index.md
> +[Turbot](https://turbot.com/) is a cloud governance and security platform with a real-time CMDB for cloud resources.
```suggestion
[Turbot Guardrails](https://turbot.com/guardrails) is the leading platform for policy-based control and automatic remediation of enterprise clouds.
```

Description taken from the site

2023-07-27 19:51 UTC, cbruno10 commented on docs/index.md
> +export TURBOT_GUARDRAILS_SECRET_KEY=3d397816-575f-4b2a-a470-a96abe29b81a
Are these the new env vars the CLI is going to use too?

2023-07-27 19:51 UTC, cbruno10 commented on docs/index.md
> +export TURBOT_PROFILE=turbot-acme
Is this going to be TURBOT_GUARDRAILS_PROFILE or remain the same (or be something else) in the CLI?

2023-07-27 19:51 UTC, cbruno10 commented on docs/tables/guardrails_control.md
> +Controls in Turbot represent the state of a given check (control type) against
```suggestion
Controls in Turbot Guardrails represent the state of a given check (control type) against
```

2023-07-27 19:51 UTC, cbruno10 commented on guardrails/table_guardrails_active_grant.go
> +		Description: "All active grants of resources by Turbot.",
```suggestion
		Description: "All active grants of resources by Turbot Guardrails.",
```

2023-07-27 19:51 UTC, cbruno10 commented on guardrails/table_guardrails_active_grant.go
> +func tableTurbotActiveGrant(ctx context.Context) *plugin.Table {
```suggestion
func tableGuardrailsActiveGrant(ctx context.Context) *plugin.Table {
```

2023-07-27 19:51 UTC, cbruno10 commented on guardrails/types.go
> +type TurbotIDObject struct {
```suggestion
type GuardrailsIDObject struct {
```

2023-07-27 20:22 UTC, misraved commented on config/guardrails.spc
> +  # Use an existing Turbot profile configured in ~/.config/turbot
Yes, the CLI  has also been rebranded to Turbot Guardrails CLI - https://turbot.com/guardrails/docs/releases/cli

2023-07-27 20:32 UTC, misraved commented on docs/index.md
> +export TURBOT_PROFILE=turbot-acme
The env variables haven't changed. I will revert [Update env variable references](https://github.com/turbot/steampipe-plugin-guardrails/pull/1/commits/5a44fe340709686762184d7e7984790c9cdde525) commit.

2023-07-28 03:23 UTC, cbruno10 approved these changes

2023-07-28 11:15 UTC, vkumbha commented on CHANGELOG.md
> +- The [Turbot](https://hub.steampipe.io/plugins/turbot/turbot/tables) tables have now been rebranded to use `Guardrails` instead:
should this be https://hub.steampipe.io/plugins/turbot/guardrails/tables ?

2023-07-28 12:39 UTC, merged